apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atomic-tickets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Pankaj-karpe/atomic-tickets-manifests.git
    targetRevision: main
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: at
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      jsonPointers:
        - /spec