apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh 
            - -c
            - until pg_isready -h postgres -p 5432 -U postgres; do sleep 2; done
      containers:
        - name: backend
          image: pankajkarpe1/atomic-tickets-pt:dafe076
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: atomic-tickets-config
            - secretRef: 
                name: atomic-tickets-secrets
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1 
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
