apiVersion: v1
kind: ConfigMap
metadata:
  name: atomic-tickets-config
  namespace: at
data:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  HOLD_EXPIRY_MINUTES: "1"
  REFUND_CUTOFF_HOURS: "24"
  BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
  FASTAPI_INTERNAL_URL: "http://backend:8000"
  PUBLIC_API_URL: "http://127.0.0.1:8000"
  SMTP_HOST: "sandbox.smtp.mailtrap.io"
  SMTP_PORT: "2525"
  FROM_EMAIL: "noreply@atomictickets.com"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.tracing.svc.cluster.local:4317"