apiVersion: v1
kind: Secret
metadata: 
  name: rabbitmq-keda-auth
  namespace: at
type: Opaque
stringData:
  host: "http://guest:guest@rabbitmq.at.svc.cluster.local:15672/"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata: 
  name: rabbitmq-trigger-auth
  namespace: at
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-keda-auth
      key: host

