# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yml
  - beat.yml
  - configmap.yml
  - ingress.yml
  - namespace.yml
  - postgres.yml
  - rabbitmq.yml
  - secret.yml
  - servicemonitor.yml
  - worker.yml
  - frontend.yml