apiVersion: v1
kind: Secret
metadata:
  name: atomic-tickets-secrets
  namespace: at
type: Opaque
stringData:
  POSTGRES_PASSWORD: "@PANKAJkarpe1"
  DATABASE_URL: "postgresql://postgres:%40PANKAJkarpe1@postgres:5432/AtomicTicket"
  SECRET_KEY: "248y5b192y4dxr9247yt0914769517c4059q7r340e5t67q92475"
  SMTP_USER: "894995b147d541"
  SMTP_PASSWORD: "13c52acb8f6356"